### ISSUE TITLE
Missing WRITE_SMS permission

### ISSUE THREAD

**Issue by leocom** [qpython-android/qpython3#62]
I have downloaded your built apk but found the WRITE_SMS permission still missing. Could you release another one with that permission included? Thanks a lot!

**Comment by riverfor** [comment]
Hello, can you try to install this version https://github.com/qpython-android/qpython3/releases/tag/2.1.0 ? 

If you have installed QPython3 from google play, you can use qpy3_2020-01-21_google.apk to replace it.

**Comment by leocom** [comment]
Sorry to tell you that even use your new apk, the WRITE_SMS is still not included.

**Comment by riverfor** [comment]
Hello,  
It looks like that the WRITE_SMS is also no longer available on Android (since API 23), even I have added it.

You can take a look at this link https://github.com/Baseflow/flutter-permission-handler/issues/25

And the below link are the test cases I have used.
https://github.com/qpython-android/qpysl4a/issues/1

If I am wrong please correct me.

Thanks.

**Comment by leocom** [comment]
I think the required permission should be SEND_SMS.
Please take a look here:
https://developer.android.com/reference/android/Manifest.permission.html#SEND_SMS

**Comment by riverfor** [comment]
Can you try to install the qpy3_2020-01-21_google.apk  https://github.com/qpython-android/qpython3/releases/tag/2.1.0  ?

I have added the permission and uploaded it again Yesterday.

**Comment by leocom** [comment]
I installed the latest version and found the permission added. However, when calling smsSend, it still threw null pointer exception.

**Comment by leocom** [comment]
I tried again and smsSend worked normally. Thanks.
